version: "3.9" # optional since v1.27.0
services:
  nginx:
    image: nginx:1.16.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
  openbooks:
    build:
      context: ../.
      dockerfile: cmd/openbooks/Dockerfile
    command: --server mock_server
    depends_on:
      - mock_server
    restart: unless-stopped
  mock_server:
    build:
      context: ../.
      dockerfile: cmd/mock_server/Dockerfile
    restart: unless-stopped
